### ISSUE TITLE
Definir modelo de dados

### ISSUE THREAD

**Issue by im-maV** [zeroCass/unb-web#3]
Objetivo é definir qual é modelo de dados para o projeto.
Desenhar um MER contendo todas as entidades envolvidas no projetos.
As entidades até então são:
- Professor
- Estudante
- Exame
- Questão

**Comment by maydMoon** [comment]
A Ideia inicial pensada para o MER foi a seguinte:

![Image](https://github.com/zeroCass/unb-web/assets/47458443/b9fa7842-c1e0-43a9-89e8-9732306664eb)

Será Necessário fazer uma alteração no banco de dados do projeto, no qual está sendo utilizado como base, para a implementação das novas entidades e seus respectivos relacionamentos.

**Comment by im-maV** [comment]
Segundo o modelo, as novas entidades terão estas caracteristicas:

1. Questao
> - id
> - id_professor
> - enunciado
> - resposta
> - tipo_questao (verdade/falso, multipla_escolha, dissertativa e numerica)

2. QuestaoMultiplaEscolha
> - id_questao
> - opcao a
> - opcao b
> - opcao c
> - opcao d

3. Exame
> - id
> - id_professor
> - id_turma
> - data_inicio
> - data_fim
> - nome
> - nota_exame (soma da quantidade de nota que cada questao tem dentro do exame)

4. QuestaoExame (Entidade Associativa)
> - id_questao
> - id_exame
> - nota_questao

5. NotasExames (armazena nota que um aluno tirou em um exame)
> - id_estudante
> - id_exame
> - nota_exame

6. RespostaQuestaoExame (resposta de um aluno para uma determinada questao dentro um exame especifico)
> - id_estudante (PK FK)
> - id_exame (PK FK)
> - id_questao (PK FK)
> - resposta_aluno
> - nota_aluno_questao
